"""empty message

Revision ID: 569a5b73df68
Revises: 0deebc2dc58e
Create Date: 2023-02-21 03:14:17.238994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569a5b73df68'
down_revision = '0deebc2dc58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
